using Sons.Items.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Mache.Utils
{
    public static class ItemsExtensions
    {
        public static int GetId(this GameItem self)
        {
            return (int)self;
        }

        public static ItemData GetData(this GameItem self)
        {
            foreach (var data in ItemDatabaseManager._instance._itemDataList)
            {
                if (data.Id == self.GetId()) return data;
            }
            return null;
        }
    }

    public enum GameItem : int
    {
        Log_Legacy = 78,
        Guitar = 340,
        Binoculars = 341,
        ShotgunRail = 346,
        GrabBag = 351,
        StunGun = 353,
        NightVisionGoggles = 354,
        CompactPistol = 355,
        ModernAxe = 356,
        Airgun = 357,
        ShotgunPumpAction = 358,
        Machete2 = 359,
        TacticalBow = 360,
        Rifle = 361,
        PistolAmmo = 362,
        SlugAmmo = 363,
        BuckshotAmmo = 364,
        Crossbow = 365,
        TrackerDart = 366,
        Katana = 367,
        CrossbowAmmoBolt = 368,
        StunGunAmmo = 369,
        PistolAmmoBox = 370,
        ShotgunAmmoBoxBuckshot = 371,
        ShotgunAmmoBoxSlug = 372,
        TacticalBowAmmo = 373,
        PistolSuppressor = 374,
        LaserSightMod = 375,
        CompactPistolRail = 376,
        ScopeMod = 377,
        FlashlightMod = 378,
        TacticalAxe = 379,
        CombatKnife = 380,
        Grenade = 381,
        GrenadeAmmo = 382,
        RifleRailMod = 383,
        CrossbowQuiverMod = 384,
        Revolver = 386,
        RifleAmmo = 387,
        Molotov = 388,
        MolotovAmmo = 389,
        PrinterResin = 390,
        RedMask = 391,
        Stick = 392,
        Rock = 393,
        TacticalChainsaw = 394,
        LogPlank = 395,
        TaserStick = 396,
        ShiitakeMushroom = 397,
        KingOysterMushroom = 398,
        HydnumRepandumMushroom = 399,
        FlyAmanitaMushroom = 400,
        TurtleEgg = 401,
        Backpack = 402,
        Rope = 403,
        Bone = 405,
        LogQuarterX1 = 406,
        LogQuarterX2 = 408,
        LogQuarterX3 = 409,
        Wristwatch = 410,
        GPSTracker = 412,
        PlasmaLighter = 413,
        VodkaBottle = 414,
        Cloth = 415,
        CircuitBoard = 416,
        TimeBomb = 417,
        Wire = 418,
        DuctTape = 419,
        C4Brick = 420,
        RamenNoodles = 421,
        RepairTool = 422,
        NovelA = 423,
        NovelB = 424,
        CerealBox = 425,
        PrintedFlask = 426,
        PrintedKnife = 427,
        PrintedSled = 428,
        PrintedUnderwaterMask = 429,
        Skull = 430,
        FireAxe = 431,
        CanOpener = 432,
        Meat = 433,
        CannedFood = 434,
        GoldMask = 435,
        Fish = 436,
        Pills = 437,
        MrePack = 438,
        EnergyDrink = 439,
        Flare = 440,
        EnergyBar = 441,
        CraftedBow = 443,
        Rebreather = 444,
        Blueberries = 445,
        Twinberries = 446,
        Salmonberries = 447,
        Snowberries = 448,
        DevilsClub = 449,
        Horsetail = 450,
        AloeVera = 451,
        Yarro = 452,
        Fireweed = 453,
        ArrowleafBalsamroot = 454,
        HealthMix = 455,
        HealthMixPlus = 456,
        StunGunAmmoBox = 457,
        BatteryCharger = 458,
        Slingshot = 459,
        BatteryPack = 460,
        EnergyMix = 461,
        EnergyMixPlus = 462,
        Flippers = 463,
        CatFood = 464,
        Chicory = 465,
        Oyster = 466,
        AlbumCover = 467,
        Cross = 468,
        AirCanister = 469,
        AirgunScope = 470,
        Flashlight = 471,
        DeerHide = 472,
        LeafArmour = 473,
        CraftedSpear = 474,
        Flask = 475,
        SmallRock = 476,
        CraftedClub = 477,
        ClimbingAxe = 478,
        Feather = 479,
        SeveredArm = 480,
        SeveredLeg = 481,
        SeveredHead = 482,
        EmergencyPack = 483,
        Leaf = 484,
        Shovel = 485,
        WalkieTalkie = 486,
        SilkPyjamas = 487,
        BlueTShirt = 488,
        TacticalPants = 489,
        Hoodie = 490,
        OldJacket = 491,
        Tuxedo = 492,
        LeatherJacket = 493,
        BoneArmour = 494,
        TacticalJacket = 495,
        Money = 496,
        FoodTray = 497,
        GRABSLaserPointer = 498,
        Wetsuit = 499,
        PuffyJacket = 500,
        TacticalBoots = 501,
        Coins = 502,
        Torch = 503,
        Tarp = 504,
        LaserMeasureTool = 505,
        TurtleShell = 506,
        CraftedArrow = 507,
        LootPouch = 508,
        BunkerPamphlet = 509,
        ContactTrigger = 511,
        FoodTrayFilled = 512,
        Spring = 513,
        ContactSpringTrigger = 514,
        TutorialPageBasicBuilding = 515,
        TutorialPageTarpTent = 516,
        CookingPot = 517,
        PaperTarget = 518,
        DeerHideArmour = 519,
        StructureElement = 520,
        EmailPrintoutCaveLighting = 521,
        RopeGun = 522,
        ZiplineRope = 523,
        GolfBall = 524,
        GolfPutter = 525,
        EmailPrintoutMrPuffyWill = 526,
        Batteries = 527,
        EmailPrintoutMrPuffyFinancial = 528,
        GPSLocator = 529,
        BlueprintDryingRack = 530,
        BlueprintStickChair = 531,
        BlueprintStickBed = 532,
        BlueprintWeaponRack = 533,
        EmailPrintoutGolfA = 534,
        EmailPrintoutGolfB = 535,
        EmailPrintoutGolfC = 536,
        EmailPrintoutGolfD = 537,
        EmailPrintoutPaintingA = 538,
        EmailPrintoutAstrologyA = 539,
        EmailPrintoutAstrologyB = 540,
        EmailPrintoutAstrologyC = 541,
        EmailPrintoutPoliticianA = 542,
        EmailPrintoutPoliticianB = 543,
        EmailPrintoutPoliticianC = 544,
        EmailPrintoutBalletA = 545,
        EmailPrintoutSqueakyShoesA = 546,
        EmailPrintoutSqueakyShoesB = 547,
        EmailPrintoutSqueakyShoesC = 548,
        BlueprintTrapBoneMaker = 549,
        BlueprintTrapFlySwatter = 550,
        BlueprintTrapSmallAnimalCatcher = 551,
        BlueprintBook = 552,
        TechMesh = 553,
        TechArmour = 554,
        VirginiaTrackSuit = 555,
        VirginiaDress = 556,
        VirginiaLeatherSuit = 557,
        VirginiaCamoSuit = 558,
        PrintedArrowHeads = 559,
        PrintedGrapplingHook = 560,
        PrintedFlowerPot = 561,
        HolovilleNoticeA = 562,
        HolovilleNoticeB = 563,
        HolovilleNoticeC = 564,
        HolovilleNoticeD = 565,
        KeyCardMaintenance = 566,
        KeyCardGuest = 567,
        KeyCardVIP = 568,
        FoodCubeBrain = 569,
        FoodCubeSteak = 570,
        FoodCubeSteakAndBacon = 571,
        GoldenArmour = 572,
        SleepingBag = 573,
        NovelC = 574,
        NovelD = 575,
        LogPlankQuarterX1 = 576,
        LogPlankQuarterX2 = 577,
        LogPlankQuarterX3 = 578,
        BlueprintBoneChair = 579,
        BlueprintStickLadder = 580,
        BlueprintBirdHouse = 581,
        BlueprintFishTrap = 582,
        BlueprintStorageBox = 583,
        BlueprintMannequin = 584,
        BlueprintScarecrow = 585,
        BlueprintPlanterWall = 586,
        BlueprintPlanterFloor = 587,
        BlueprintBoneChandelier = 588,
        TutorialBook = 589,
        Radio = 590,
        BlueprintSmallLogCabin = 591,
        CreepySkin = 592,
        CreepyArmour = 593,
        GuaranaBerries = 594,
        Blackberries = 595,
        AloeVeraSeed = 596,
        ArrowleafSeed = 597,
        BlackberrySeed = 598,
        BlueberrySeed = 599,
        DevilsClubSeed = 600,
        FireweedSeed = 601,
        GuaranaSeed = 602,
        HorsetailSeed = 603,
        SalmonberrySeed = 604,
        ChicorySeed = 605,
        YarroSeed = 606,
        BlueprintStorageRocks = 607,
        BlueprintStorageBones = 608,
        BlueprintStorageLogs = 609,
        BlueprintStorageSticks = 610,
        NumbersPrintout = 611,
        NewspaperCutout = 612,
        NewspaperCutoutOutbid = 613,
        EmailPrintoutGovernmentA = 614,
        EmailPrintoutGovernmentB = 615,
        EmailPrintoutGovernmentC = 616,
        StockPricePrintout = 617,
        PrintedArrow = 618,
        VirginiaSwimSuit = 619,
        BlueprintTable = 620,
        BlueprintShelf = 621,
        BlueprintRockPath = 622,
        BlueprintWallShelf = 623,
        BlueprintWallTorch = 624,
        BlueprintHangingSkullLight = 625
    }
}
